name: CI/CD Deploy Java App to Tomcat10 on EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Build WAR using Maven
      - name: Build WAR file
        run: mvn clean package -DskipTests

      # 4️⃣ Find and rename WAR file to ROOT.war
      - name: Prepare WAR file
        run: |
          echo "=== Checking for WAR files ==="
          ls -la target/
          WAR_FILE=$(ls target/*.war | head -1)
          echo "Found WAR: $WAR_FILE"
          cp "$WAR_FILE" ROOT.war

      # 5️⃣ Create SSH key
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 6️⃣ Copy WAR file to EC2
      - name: Copy WAR file to EC2
        run: |
          echo "=== Uploading WAR to EC2 ==="
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ROOT.war ubuntu@${{ secrets.EC2_HOST }}:/tmp/ROOT.war

      # 7️⃣ Deploy on EC2
      - name: Deploy on Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Deployment ==="

            # Stop Tomcat
            sudo systemctl stop tomcat10 || true

            # Clean previous deployment
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT*
            
            # Move new WAR
            sudo mv /tmp/ROOT.war /var/lib/tomcat10/webapps/

            # Set permissions
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 644 /var/lib/tomcat10/webapps/ROOT.war

            echo "=== Starting Tomcat ==="
            sudo systemctl start tomcat10

            echo "Waiting for Tomcat to start..."
            sleep 25

            echo "=== Deployment completed. Checking files ==="
            ls -la /var/lib/tomcat10/webapps/
            sudo systemctl status tomcat10 --no-pager

            echo "If ROOT.war exists, Tomcat will auto-extract files inside ROOT/ automatically."

